### ISSUE TITLE
How to build correctly on linux?

### ISSUE THREAD

**Issue by LeavesOfFruit** [Hork-Engine/Hork-Source#2]
Helo @0xc0de 

I've tried to build this on unix, by git cloning this repo (using recurse-submodules), and running `cmake..` then the `make` command. But I'm getting huge error log, which keeps repeating this error:
```
/home/mm/Desktop/Hork-Source/Source/./Core/BaseMath.h:1377:33: error: could not convert ‘value.TSprintfBuffer<32>::Sprintf(format.Data, (* reinterpret_cast<const uint16_t*>(& _Value)))’ from ‘char*’ to ‘AString’
 1377 |             return value.Sprintf(format.Data, *reinterpret_cast<const uint16_t*>(&_Value));
      |                    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                 |
      |                                 char*

```
In the project desc it mentions linux as a supported platform. But how do I build it correctly ? Am I missing a steps in the cmake process?

**Comment by 0xc0de** [comment]
Hello, [LeavesOfFruit](https://github.com/LeavesOfFruit)
What compiler are you using? Try to fix function signature from char* Sprintf(const char* _Format, ...) to const char* Sprintf(const char* _Format, ...). Please let me know if it helped.

**Comment by LeavesOfFruit** [comment]
Hi

Thank for the reply. I have now changed the return types to `return const value.Sprintf(format.Data, *reinterpret_cast<const uint8_t*>(&_Value));`
But I'm still getting many errors:
```
/home/mm/Desktop/Hork-Source/Source/Core/BaseMath.h:1389:24: error: expected primary-expression before ‘const’
 1389 |                 return const value.Sprintf("%s%I64x", prefixStr, Temp);
      |                        ^~~~~
/home/mm/Desktop/Hork-Source/Source/Core/BaseMath.h:1389:23: error: expected ‘;’ before ‘const’
 1389 |                 return const value.Sprintf("%s%I64x", prefixStr, Temp);
      |                       ^~~~~~
      |                       ;
/home/mm/Desktop/Hork-Source/Source/Core/BaseMath.h:1389:30: error: ‘value’ does not name a type
 1389 |                 return const value.Sprintf("%s%I64x", prefixStr, Temp);
      |                              ^~~~~
```
In addition, Im getting errors with `Memory.h` files as well:
```
/home/mm/Desktop/Hork-Source/Source/./Platform/Memory/Memory.h: In function ‘void Platform::Memset(void*, int, size_t)’:
/home/mm/Desktop/Hork-Source/Source/./Platform/Memory/Memory.h:76:14: error: ‘memset’ is not a member of ‘std’; did you mean ‘wmemset’?
   76 |         std::memset(_Dst, _Val, _SizeInBytes);
      |              ^~~~~~
      |              wmemset

```
Which linux distro have you managed to build Hork on? Did you use any special configs to get it to build?

**Comment by tree786isback** [comment]
> Hello, [LeavesOfFruit](https://github.com/LeavesOfFruit) Try to fix function signature from char* Sprintf(const char* _Format, ...) to const char* Sprintf(const char* _Format, ...). Please let me know if it helped.

Hi 

Which line of code should I change to being a `const char*`? Could you show me an example of which line should be changed to it? Thank z

**Comment by LeavesOfFruit** [comment]
> Hello, [LeavesOfFruit](https://github.com/LeavesOfFruit) Try to fix function signature from char* Sprintf(const char* _Format, ...) to const char* Sprintf(const char* _Format, ...). Please let me know if it helped.

Hi

Which line of code should I change to being a const char*? Could you show me an example of which line should be changed to it? Thank z

**Comment by 0xc0de** [comment]
Please update to the latest version. I just fixed the build on GCC.

**Comment by LeavesOfFruit** [comment]
Thank ver much ! I've just managed to compile it now!
