### ISSUE TITLE
different loggers and ability to specify where to log

### ISSUE THREAD

**Issue by brightening-eyes** [Hork-Engine/Hork-Source#20]
hello.
for CoreApplication::log(), it should be possible to specify loggers. for example, it should be possible to have a logger class to log to console, while another can be present to log messages with OutputDebugString on windows and so on.
this way, it is possible to disable logging messages on release builds as well.

**Comment by 0xc0de** [comment]
Implemented in [7c1e20e](https://github.com/Hork-Engine/Hork-Source/commit/7c1e20e1c75a7c7e98c2570f7ef4a83be009f7ca)
