### ISSUE TITLE
Why audio is low quality

### ISSUE THREAD

**Issue by YupCore** [Hork-Engine/Hork-Source#4]
It sounds like its 8 bit and forced mono but why?
Here's my code to load a sound

        STransform audioTransfrom;
        audioTransfrom.Position = Float3(0, 1, 0);
        audioTransfrom.Rotation = Quat::Identity();
        audioTransfrom.Scale    = Float3(1);

        ASoundResource* sound      = GetOrCreateResource<ASoundResource>("/Root/goal1.mp3");
        AActor*         audioPoint = world->SpawnActor2(audioTransfrom);
        ASoundEmitter*  pl         = audioPoint->CreateComponent<ASoundEmitter>("AudioSource");

        ASoundGroup* s = new ASoundGroup();
        s->SetVolume(1);
        s->SetPaused(false);
        pl->SetEmitterType(ESoundEmitterType::SOUND_EMITTER_POINT);
        pl->SetRolloffRate(0.01f);
        pl->SetMaxDistance(400);
        pl->SetReferenceDistance(1);

        pl->PlaySoundAt(world, sound, s, audioTransfrom.Position);

**Comment by 0xc0de** [comment]
ASoundEmitter::PlaySoundAt is a static method, so ASoundEmitter should not be instantiated. Your code will be simplified to the following:
```
        ASoundResource* sound = GetOrCreateResource<ASoundResource>("/Root/goal1.mp3");
        ASoundGroup*  s  = new ASoundGroup();
        s->SetVolume(1);
        s->SetPaused(false);
        ASoundEmitter::PlaySoundAt(world, sound, s, Float3(0, 1, 0));
        // or  ASoundEmitter::PlaySoundBackground(world, sound, s);
```

The HRTF filter is enabled by default. Try turning it off, it may improve the sound quality in your case. The HRTF filter can be disabled with the snd_HRTF 0 console command.
